name: 'Setup Java'
description: 'Set up a specific version of Java'
inputs:
  distribution:
    description: 'Java distribution'
    required: true
  java-version:
    description: 'Java version'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-${{ inputs.java-version }}-jdk
